### ISSUE TITLE
Exception when using audit-argument-checks package

### ISSUE THREAD

**Issue by ronaldocpontes** [radiegtya/meteoris2#90]
How to replicate:

```
git clone git@github.com:radiegtya/meteoris2.git
cd meteoris2
meteor add audit-argument-checks
meteor

# go to: http://localhost:3000/
```

Exception:
```
[15:25:32] $ meteor
[[[[[ ~/code/meteoris2 ]]]]]                  

=> Started proxy.                             
=> Meteor 1.2.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
I20151020-15:25:46.711(1)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Started your app.

=> App running at: http://localhost:3000/
                                              
Changes to your project's package version selections:
                                              
audit-argument-checks  added, version 1.0.3   

I20151020-15:27:42.209(1)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Meteor server restarted
I20151020-15:27:54.614(1)? Exception while invoking method 'MugenRoleActions.getRoles' Error: Did not check() all arguments during call to 'MugenRoleActions.getRoles'
I20151020-15:27:54.614(1)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20151020-15:27:54.614(1)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20151020-15:27:54.614(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20151020-15:27:54.614(1)?     at packages/ddp/livedata_server.js:648:1
I20151020-15:27:54.614(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151020-15:27:54.614(1)?     at packages/ddp/livedata_server.js:647:1
I20151020-15:27:54.614(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151020-15:27:54.614(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20151020-15:27:54.615(1)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by radiegtya** [comment]
Sorry this repo is still inactive. ASAP I'll publish the latest meteoris with rewrite all of the engine. If you still want to use, please use the v1 rather than v2.
